### ISSUE TITLE
希望能添加github.io的解析

### ISSUE THREAD

**Issue by sage9731** [ButterAndButterfly/GithubHost#43]
感谢这个项目让我在github重现看到了图片！

另外，github.io也经常访问不了，希望能添加github.io的解析。

**Comment by nICEnnnnnnnLee** [comment]
+ 不支持泛域名解析，像`*.github.io`这种是没辙的，只能对应到具体域名。
+ 单个域名建议人工进行查询，比如国内国外都ping一下看看差异，或者直接查询dns。这种工具站很多的，比如
    + http://ping.chinaz.com/ 
    + https://www.ipaddress.com/
