### ISSUE TITLE
[Issue] GitHub登入的认证域名也无法访问

### ISSUE THREAD

**Issue by gongxw** [ButterAndButterfly/GithubHost#69]
GitHub登入的认证域名也无法访问

**Comment by nICEnnnnnnnLee** [comment]
无论改host还是裸连，最近github都是有时能上有时不能上。(当然，某些域名仍然被DNS污染，也就是裸连仍旧看不到图)
在连通期间，我试了一下登录github，比较顺利。
以上。
这不是改host能解决的问题了。

**Comment by gongxw** [comment]
是我没表述清楚。我是指第三方使用GitHub账号登录时用到的认证地址，比如vscode登录时的认证地址域名是https://vscode-auth.github.com。这种情况是否能通过host方式解决呢。

**Comment by nICEnnnnnnnLee** [comment]
经测试，在**可以直连github的时候**，vscode授权没有问题。(可能网络会因为地区而有所差异)
